version: '3.4'

services:
  tiendaservicios.api.autor:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "6104:80"
      #- "443"
    #volumes:
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  tiendaservicios.api.libro:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:444;http://+:80
    ports:
      - "6105:80"
      #- "444"
    #volumes:
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  tiendaservicios.api.carritocompra:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Libros=http://tiendaservicios.api.libro 
      #//Reemplaza la url del microservice definida en carrtio...
      #- ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "6106:80"
      #- "443"
    #volumes:
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  tiendaservicios.api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - tiendaservicios.api.libro
    ports:
      - "6107:80"

